### ISSUE TITLE
can't import the jar in windows - webstorm 10

### ISSUE THREAD

**Issue by udisun** [minwe/jetbrains-react#1]
![screenshot 2015-09-23 12 21 06](https://cloud.githubusercontent.com/assets/950100/10041558/9ec0347c-61ed-11e5-87f7-2bd407bc01ab.png)

**Comment by minwe** [comment]
I tested on Window 7 + WebStorm 10.4, also Windows 10 + WS 10.4, it works well.

Try to redownload from https://raw.githubusercontent.com/minwe/jetbrains-react/master/jetbrains-react.jar.

**Comment by M3lkior** [comment]
It works for me with your link but not by directly dowloading the jar in Github code tab

**Comment by minwe** [comment]
Use the latest version of WebStorm, please.
