### ISSUE TITLE
Select Components to Import is empty in WebStorm 11 EAP 143.88

### ISSUE THREAD

**Issue by doxxx** [minwe/jetbrains-react#2]
After selecting the jar, WebStorm displays a dialog entitled "Select Components to Import". However, the list is empty. Clicking Okay doesn't seem to import anything -- there's no React group in the Live Templates after restarting WebStorm.

**Comment by minwe** [comment]
Try to install manually, just download and copy `ReactJS.xml` to:

```
~/Library/Preferences/WebStorm11/templates/
```

Then check the `ReactJS` live templates group in settings.

I'll check why the jar file not working on WS11 later.

**Comment by minwe** [comment]
It maybe caused by some bugs of WebStorm EAP version.

The latest EAP build `143.88` can't export any live templates, so importing live templates may not working, too.

**Comment by minwe** [comment]
@doxxx  

WebStorm 11 Public preview, 143.267 seems fixed the bug, you can import  live templates on the new version.

http://blog.jetbrains.com/webstorm/2015/10/webstorm-11-public-preview-143-267-fixes/

**Comment by doxxx** [comment]
Thanks, I'll check it out.
