### ISSUE TITLE
Is there a way to import settings with 4 spaces indent?

### ISSUE THREAD

**Issue by alexeychikk** [minwe/jetbrains-react#3]

**Comment by minwe** [comment]
No way at present except you adjust templates manually.

You can reformat code after everything done by `Command + Alt + L`.

Most of React projects use 2 spaces indent, for example React, React Router.

I will check the possibility of 4 spaces indent version later.

**Comment by minwe** [comment]
Sorry, there is an option, which reformat template according your code style settings.

I have enabled it on [the latest release](https://github.com/minwe/jetbrains-react/releases/tag/v2.4.0). You can re-download and try it now.
