### ISSUE TITLE
Cannot import in PHPStorm 2016.2.2

### ISSUE THREAD

**Issue by vklein** [minwe/jetbrains-react#6]
Hi,
thx for your live templates. I used them a lot. 

But since PHPStorm 2016.2.\* its not possible for me to import the Live-Templates. 
I tried the import and the manual import.

Do you have an idea? Or is it a known bug?

**Comment by minwe** [comment]
I download PHPStorm `2016.2.2` and import live templates just now, it works well.

What's wrong with you?

**Comment by vklein** [comment]
Thanks for your quick response.

Thats a really good question ;)

It was a problem with the "settings repository" plugin in phpstorm. I deactivate it and now everything works ;)
